"""
Export an offline snapshot of the BookMe data for the app.

The app always tries the live API first (backend/main.py). If the API isn't
running, it falls back to this snapshot so the demo still works anywhere,
including when the page is opened straight from the file system.

The queries mirror the ones in backend/main.py so the snapshot has the same
shape as the API responses. Re-run this whenever synthetic_data/dining_app.db
is regenerated:

    python3 frontend-app/tools/export_snapshot.py
"""

import json
import os
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(ROOT, "synthetic_data", "dining_app.db")
OUT_PATH = os.path.join(ROOT, "frontend-app", "data", "snapshot.js")


def rows(conn, sql, params=()):
    return [dict(r) for r in conn.execute(sql, params).fetchall()]


def main():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    restaurants = rows(conn, """
        SELECT restaurant_id, name, description, cuisine_type, price_tier, address_line1,
               neighborhood, city, latitude, longitude, seats_total, avg_prep_time_minutes,
               avg_rating, total_reviews, health_inspection_score
        FROM restaurants WHERE is_active = 1 ORDER BY restaurant_id""")

    users = rows(conn, """
        SELECT u.user_id, u.full_name, u.home_neighborhood, u.favorite_cuisine,
               u.price_sensitivity, GROUP_CONCAT(dt.name) AS dietary_tags
        FROM users u
        LEFT JOIN user_dietary_tags udt ON udt.user_id = u.user_id
        LEFT JOIN dietary_tags dt ON dt.dietary_tag_id = udt.dietary_tag_id
        GROUP BY u.user_id
        ORDER BY (dietary_tags IS NULL), u.user_id
        LIMIT 40""")

    # Full menus with allergens, same fields as GET /restaurants/{id}/menu,
    # plus prep_time_minutes so the offline ETA can use the same formula.
    menus = {}
    for r in restaurants:
        rid = r["restaurant_id"]
        items = rows(conn, """
            SELECT mi.item_id, mi.name, mi.description, mi.price, mi.discount_price,
                   mc.name AS category, mi.is_vegetarian, mi.is_vegan, mi.is_gluten_free,
                   mi.popularity_score, mi.prep_time_minutes, mi.spice_level, mi.calories
            FROM menu_items mi
            LEFT JOIN menu_categories mc ON mc.category_id = mi.category_id
            WHERE mi.restaurant_id = ? AND mi.is_available = 1""", (rid,))
        for it in items:
            it["allergens"] = [a["name"] for a in rows(conn, """
                SELECT a.name FROM menu_item_allergens mia
                JOIN allergens a ON a.allergen_id = mia.allergen_id
                WHERE mia.item_id = ?""", (it["item_id"],))]
            it["modifiers"] = rows(conn, """
                SELECT modifier_id, name, price_delta FROM item_modifiers
                WHERE item_id = ?""", (it["item_id"],))
        menus[rid] = items

    tables = {}
    for r in restaurants:
        tables[r["restaurant_id"]] = rows(conn, """
            SELECT table_id, table_number, capacity, location_zone, seating_feature, status
            FROM restaurant_tables WHERE restaurant_id = ?""", (r["restaurant_id"],))

    # Confirmed (upcoming) bookings, used to mark tables as reserved on the
    # live-seats screen. The API has no reservations endpoint yet.
    reservations = {}
    for r in restaurants:
        reservations[r["restaurant_id"]] = rows(conn, """
            SELECT reservation_id, table_id, party_size, reservation_time
            FROM reservations WHERE restaurant_id = ? AND status = 'confirmed'
            ORDER BY reservation_time""", (r["restaurant_id"],))

    # Full forecast history (the API returns 8 rows per call; the dashboard
    # asks for one date at a time, so the snapshot keeps every date).
    forecast = {}
    for r in restaurants:
        forecast[r["restaurant_id"]] = rows(conn, """
            SELECT forecast_id, shift_date, shift_block, predicted_covers, actual_covers,
                   recommended_staff_count, actual_staff_count, confidence_score,
                   weather_condition, is_holiday, local_event_nearby
            FROM staffing_forecast WHERE restaurant_id = ?
            ORDER BY shift_date, shift_block""", (r["restaurant_id"],))

    wages = {}
    for r in restaurants:
        row = conn.execute(
            "SELECT AVG(hourly_wage) AS w FROM restaurant_staff WHERE restaurant_id = ? AND is_active = 1",
            (r["restaurant_id"],)).fetchone()
        wages[r["restaurant_id"]] = round(row["w"] or 0, 2)

    snapshot = {
        "source": "synthetic_data/dining_app.db",
        "restaurants": restaurants,
        "users": users,
        "menus": menus,
        "tables": tables,
        "reservations": reservations,
        "forecast": forecast,
        "avg_hourly_wage": wages,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("// Generated by frontend-app/tools/export_snapshot.py. Do not edit by hand.\n")
        f.write("window.BOOKME_SNAPSHOT = ")
        json.dump(snapshot, f, separators=(",", ":"))
        f.write(";\n")
    print(f"Wrote {OUT_PATH} ({os.path.getsize(OUT_PATH) // 1024} KB)")


if __name__ == "__main__":
    main()
